### ISSUE TITLE
Mod crashes game whenever I try to collect quest rewards

### ISSUE THREAD

**Issue by mrpeeps** [CleanroomMC/BetterQuesting#64]
Ive been trying to play the modpack "Multiblock Madness" but every time I click "collect rewards" for a quest, the game crashes.
Log:
[crash-2022-08-20_11.00.27-client.txt](https://github.com/CleanroomMC/BetterQuesting/files/9410850/crash-2022-08-20_11.00.27-client.txt)
 Originally, I posted this on the modpacks github page, but they claimed it was just an issue with this mod, and to post it directly here.

**Comment by ALongStringOfNumbers** [comment]
Sorry for the delay, this should be fixed in #66
