### ISSUE TITLE
Unable to join a party

### ISSUE THREAD

**Issue by Grekorian** [CleanroomMC/BetterQuesting#68]
On a server I and my friend were unable to join each other's parties, nor even see the invites. Console said nothing was wrong, so I do not know what to do. Any ideas?

**Comment by WaitingIdly** [comment]
you cannot join another party if you are already in one - did you make sure to leave your current party when attempting to join the other?

**Comment by Grekorian** [comment]
That was it, thank you

**Comment by ALongStringOfNumbers** [comment]
Closing this since the issue was solved.
