### ISSUE TITLE
Hidden Quests Visible in View Mode

### ISSUE THREAD

**Issue by TFCAliarcy** [CleanroomMC/BetterQuesting#83]
When set to view mode you can see quests that are marked as hidden and those marked as visible upon completion, this makes it so those quests are visible to all. This is different to GTNH which only lets you see hidden quests when in edit mode.

**Comment by WaitingIdly** [comment]
BQu allows you to control the behavior of all quests in the same manner via setting the `ignoresView` property to true.

**Comment by TFCAliarcy** [comment]
> BQu allows you to control the behavior of all quests in the same manner via setting the `ignoresView` property to true.

Thanks, I was not aware of this.

**Comment by WaitingIdly** [comment]
this is not an issue, and is working as intended: `view` mode being enabled should override the visibility of the quest unless `ignoresView` is true on that quest.
