### ISSUE TITLE
Current quest file format is not git-friendly

### ISSUE THREAD

**Issue by KatatsumuriPan** [CleanroomMC/BetterQuesting#93]
Removing quest causes the commit to become too large.
[This is an example.](https://github.com/GTModpackTeam/GregTech-Expert-2/commit/b008b3bafc879ac5015a2595e9b5fe2681e58405)

To fix it, I suggest using NBTTagCompound keyed by questID instead of NBTTagList.
This changes the format of the quest file(DefaultQuests.json) and breaks forward compatibility.

**Comment by KatatsumuriPan** [comment]
Additionally, I don't think BQ's unique file format is human-friendly.
I recommend using Key-Sorted-SNBT.(original SNBT keys are randomly sorted...)

**Comment by KatatsumuriPan** [comment]
Furthermore, splitting quest files like gtnh is better.

**Comment by WaitingIdly** [comment]
resolved by #111 splitting quest files.
