### ISSUE TITLE
[SUGGESTION] Make it possible to have multiple JSON files for multiple quest lines

### ISSUE THREAD

**Issue by joendter** [CleanroomMC/BetterQuesting#94]
Currently all quests are thrown into 1 json file, which doesn't behave nicely if you want to use git to merge multiple branches.
It would be nice to be able to have separate quest lines in separate json files. It would already be incredibly helpful in a state where quests from different files can't interact with another (dependencies etc.) but are only displayed in as their own chapters in the quest book.

**Comment by WaitingIdly** [comment]
this has been resolved by #111
