### ISSUE TITLE
External quest editor broken & missing features

### ISSUE THREAD

**Issue by jacket430** [CleanroomMC/BetterQuesting#97]
Hey there, 

I appreciate having a new option to edit quests and the work that was put into the new editor, but at least using ATLauncher, it's completely broken at the moment. 

Upon finishing the quest description, pressing the "done" button just closes the window and doesn't input the text into the game. I've tried this on a fresh install and on my current WIP pack, and both have the same results. So unless I want to write the quests entirely out in the description box without formatting, quest descriptions can't be written with 4.2.0. I haven't seen anything popping up in the logs either. 

Aside from that, the new editor doesn't appear to have the ability to preview your text formatting as you work on the quest descriptions anymore. After using the original editor for a while it's definitely a frustrating removal, on top of it just not working in the first place. 

Not having an option to switch back to the original in-game editor essentially makes updating from 4.1.0 a no-go.

**Comment by Rongmario** [comment]
Thank you for the heads up, I can replicate this with latest after the initial edit. I'll take a look.

**Comment by Rongmario** [comment]
Fixed in dev.
